/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiColegioRouteImport } from './routes/mi-colegio'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocentesRouteImport } from './routes/docentes'
import { Route as CreRouteImport } from './routes/cre'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CircularesRouteImport } from './routes/circulares'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BienestarRouteImport } from './routes/bienestar'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmisionesRouteImport } from './routes/admisiones'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIdRouteImport } from './routes/noticias.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSuscriptoresIndexRouteImport } from './routes/_authenticated/admin/suscriptores/index'
import { Route as AuthenticatedAdminPreinscripcionesIndexRouteImport } from './routes/_authenticated/admin/preinscripciones/index'
import { Route as AuthenticatedAdminNoticiasIndexRouteImport } from './routes/_authenticated/admin/noticias/index'
import { Route as AuthenticatedAdminMensajesIndexRouteImport } from './routes/_authenticated/admin/mensajes/index'
import { Route as AuthenticatedAdminLibrosIndexRouteImport } from './routes/_authenticated/admin/libros/index'
import { Route as AuthenticatedAdminGaleriaIndexRouteImport } from './routes/_authenticated/admin/galeria/index'
import { Route as AuthenticatedAdminFaqsIndexRouteImport } from './routes/_authenticated/admin/faqs/index'
import { Route as AuthenticatedAdminEventosIndexRouteImport } from './routes/_authenticated/admin/eventos/index'
import { Route as AuthenticatedAdminDocumentosIndexRouteImport } from './routes/_authenticated/admin/documentos/index'
import { Route as AuthenticatedAdminDocentesIndexRouteImport } from './routes/_authenticated/admin/docentes/index'
import { Route as AuthenticatedAdminCarruselIndexRouteImport } from './routes/_authenticated/admin/carrusel/index'
import { Route as AuthenticatedAdminAvisosIndexRouteImport } from './routes/_authenticated/admin/avisos/index'
import { Route as AuthenticatedAdminAsistenteIndexRouteImport } from './routes/_authenticated/admin/asistente/index'
import { Route as AuthenticatedAdminNoticiasNuevaRouteImport } from './routes/_authenticated/admin/noticias/nueva'
import { Route as AuthenticatedAdminGaleriaNuevaRouteImport } from './routes/_authenticated/admin/galeria/nueva'
import { Route as AuthenticatedAdminDocumentosNuevoRouteImport } from './routes/_authenticated/admin/documentos/nuevo'

const MiColegioRoute = MiColegioRouteImport.update({
  id: '/mi-colegio',
  path: '/mi-colegio',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesRoute = DocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreRoute = CreRouteImport.update({
  id: '/cre',
  path: '/cre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularesRoute = CircularesRouteImport.update({
  id: '/circulares',
  path: '/circulares',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BienestarRoute = BienestarRouteImport.update({
  id: '/bienestar',
  path: '/bienestar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmisionesRoute = AdmisionesRouteImport.update({
  id: '/admisiones',
  path: '/admisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIdRoute = NoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSuscriptoresIndexRoute =
  AuthenticatedAdminSuscriptoresIndexRouteImport.update({
    id: '/admin/suscriptores/',
    path: '/admin/suscriptores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPreinscripcionesIndexRoute =
  AuthenticatedAdminPreinscripcionesIndexRouteImport.update({
    id: '/admin/preinscripciones/',
    path: '/admin/preinscripciones/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNoticiasIndexRoute =
  AuthenticatedAdminNoticiasIndexRouteImport.update({
    id: '/admin/noticias/',
    path: '/admin/noticias/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMensajesIndexRoute =
  AuthenticatedAdminMensajesIndexRouteImport.update({
    id: '/admin/mensajes/',
    path: '/admin/mensajes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLibrosIndexRoute =
  AuthenticatedAdminLibrosIndexRouteImport.update({
    id: '/admin/libros/',
    path: '/admin/libros/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGaleriaIndexRoute =
  AuthenticatedAdminGaleriaIndexRouteImport.update({
    id: '/admin/galeria/',
    path: '/admin/galeria/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFaqsIndexRoute =
  AuthenticatedAdminFaqsIndexRouteImport.update({
    id: '/admin/faqs/',
    path: '/admin/faqs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEventosIndexRoute =
  AuthenticatedAdminEventosIndexRouteImport.update({
    id: '/admin/eventos/',
    path: '/admin/eventos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocumentosIndexRoute =
  AuthenticatedAdminDocumentosIndexRouteImport.update({
    id: '/admin/documentos/',
    path: '/admin/documentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocentesIndexRoute =
  AuthenticatedAdminDocentesIndexRouteImport.update({
    id: '/admin/docentes/',
    path: '/admin/docentes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCarruselIndexRoute =
  AuthenticatedAdminCarruselIndexRouteImport.update({
    id: '/admin/carrusel/',
    path: '/admin/carrusel/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAvisosIndexRoute =
  AuthenticatedAdminAvisosIndexRouteImport.update({
    id: '/admin/avisos/',
    path: '/admin/avisos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAsistenteIndexRoute =
  AuthenticatedAdminAsistenteIndexRouteImport.update({
    id: '/admin/asistente/',
    path: '/admin/asistente/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNoticiasNuevaRoute =
  AuthenticatedAdminNoticiasNuevaRouteImport.update({
    id: '/admin/noticias/nueva',
    path: '/admin/noticias/nueva',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGaleriaNuevaRoute =
  AuthenticatedAdminGaleriaNuevaRouteImport.update({
    id: '/admin/galeria/nueva',
    path: '/admin/galeria/nueva',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocumentosNuevoRoute =
  AuthenticatedAdminDocumentosNuevoRouteImport.update({
    id: '/admin/documentos/nuevo',
    path: '/admin/documentos/nuevo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admisiones': typeof AdmisionesRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/bienestar': typeof BienestarRoute
  '/calendario': typeof CalendarioRoute
  '/circulares': typeof CircularesRoute
  '/contacto': typeof ContactoRoute
  '/cre': typeof CreRoute
  '/docentes': typeof DocentesRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/guias': typeof GuiasRoute
  '/herramientas': typeof HerramientasRoute
  '/mi-colegio': typeof MiColegioRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/documentos/nuevo': typeof AuthenticatedAdminDocumentosNuevoRoute
  '/admin/galeria/nueva': typeof AuthenticatedAdminGaleriaNuevaRoute
  '/admin/noticias/nueva': typeof AuthenticatedAdminNoticiasNuevaRoute
  '/admin/asistente/': typeof AuthenticatedAdminAsistenteIndexRoute
  '/admin/avisos/': typeof AuthenticatedAdminAvisosIndexRoute
  '/admin/carrusel/': typeof AuthenticatedAdminCarruselIndexRoute
  '/admin/docentes/': typeof AuthenticatedAdminDocentesIndexRoute
  '/admin/documentos/': typeof AuthenticatedAdminDocumentosIndexRoute
  '/admin/eventos/': typeof AuthenticatedAdminEventosIndexRoute
  '/admin/faqs/': typeof AuthenticatedAdminFaqsIndexRoute
  '/admin/galeria/': typeof AuthenticatedAdminGaleriaIndexRoute
  '/admin/libros/': typeof AuthenticatedAdminLibrosIndexRoute
  '/admin/mensajes/': typeof AuthenticatedAdminMensajesIndexRoute
  '/admin/noticias/': typeof AuthenticatedAdminNoticiasIndexRoute
  '/admin/preinscripciones/': typeof AuthenticatedAdminPreinscripcionesIndexRoute
  '/admin/suscriptores/': typeof AuthenticatedAdminSuscriptoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admisiones': typeof AdmisionesRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/bienestar': typeof BienestarRoute
  '/calendario': typeof CalendarioRoute
  '/circulares': typeof CircularesRoute
  '/contacto': typeof ContactoRoute
  '/cre': typeof CreRoute
  '/docentes': typeof DocentesRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/guias': typeof GuiasRoute
  '/herramientas': typeof HerramientasRoute
  '/mi-colegio': typeof MiColegioRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/documentos/nuevo': typeof AuthenticatedAdminDocumentosNuevoRoute
  '/admin/galeria/nueva': typeof AuthenticatedAdminGaleriaNuevaRoute
  '/admin/noticias/nueva': typeof AuthenticatedAdminNoticiasNuevaRoute
  '/admin/asistente': typeof AuthenticatedAdminAsistenteIndexRoute
  '/admin/avisos': typeof AuthenticatedAdminAvisosIndexRoute
  '/admin/carrusel': typeof AuthenticatedAdminCarruselIndexRoute
  '/admin/docentes': typeof AuthenticatedAdminDocentesIndexRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosIndexRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosIndexRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsIndexRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaIndexRoute
  '/admin/libros': typeof AuthenticatedAdminLibrosIndexRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesIndexRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasIndexRoute
  '/admin/preinscripciones': typeof AuthenticatedAdminPreinscripcionesIndexRoute
  '/admin/suscriptores': typeof AuthenticatedAdminSuscriptoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admisiones': typeof AdmisionesRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/bienestar': typeof BienestarRoute
  '/calendario': typeof CalendarioRoute
  '/circulares': typeof CircularesRoute
  '/contacto': typeof ContactoRoute
  '/cre': typeof CreRoute
  '/docentes': typeof DocentesRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/guias': typeof GuiasRoute
  '/herramientas': typeof HerramientasRoute
  '/mi-colegio': typeof MiColegioRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/documentos/nuevo': typeof AuthenticatedAdminDocumentosNuevoRoute
  '/_authenticated/admin/galeria/nueva': typeof AuthenticatedAdminGaleriaNuevaRoute
  '/_authenticated/admin/noticias/nueva': typeof AuthenticatedAdminNoticiasNuevaRoute
  '/_authenticated/admin/asistente/': typeof AuthenticatedAdminAsistenteIndexRoute
  '/_authenticated/admin/avisos/': typeof AuthenticatedAdminAvisosIndexRoute
  '/_authenticated/admin/carrusel/': typeof AuthenticatedAdminCarruselIndexRoute
  '/_authenticated/admin/docentes/': typeof AuthenticatedAdminDocentesIndexRoute
  '/_authenticated/admin/documentos/': typeof AuthenticatedAdminDocumentosIndexRoute
  '/_authenticated/admin/eventos/': typeof AuthenticatedAdminEventosIndexRoute
  '/_authenticated/admin/faqs/': typeof AuthenticatedAdminFaqsIndexRoute
  '/_authenticated/admin/galeria/': typeof AuthenticatedAdminGaleriaIndexRoute
  '/_authenticated/admin/libros/': typeof AuthenticatedAdminLibrosIndexRoute
  '/_authenticated/admin/mensajes/': typeof AuthenticatedAdminMensajesIndexRoute
  '/_authenticated/admin/noticias/': typeof AuthenticatedAdminNoticiasIndexRoute
  '/_authenticated/admin/preinscripciones/': typeof AuthenticatedAdminPreinscripcionesIndexRoute
  '/_authenticated/admin/suscriptores/': typeof AuthenticatedAdminSuscriptoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admisiones'
    | '/auth'
    | '/biblioteca'
    | '/bienestar'
    | '/calendario'
    | '/circulares'
    | '/contacto'
    | '/cre'
    | '/docentes'
    | '/faq'
    | '/galeria'
    | '/guias'
    | '/herramientas'
    | '/mi-colegio'
    | '/noticias/$id'
    | '/admin/'
    | '/admin/documentos/nuevo'
    | '/admin/galeria/nueva'
    | '/admin/noticias/nueva'
    | '/admin/asistente/'
    | '/admin/avisos/'
    | '/admin/carrusel/'
    | '/admin/docentes/'
    | '/admin/documentos/'
    | '/admin/eventos/'
    | '/admin/faqs/'
    | '/admin/galeria/'
    | '/admin/libros/'
    | '/admin/mensajes/'
    | '/admin/noticias/'
    | '/admin/preinscripciones/'
    | '/admin/suscriptores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admisiones'
    | '/auth'
    | '/biblioteca'
    | '/bienestar'
    | '/calendario'
    | '/circulares'
    | '/contacto'
    | '/cre'
    | '/docentes'
    | '/faq'
    | '/galeria'
    | '/guias'
    | '/herramientas'
    | '/mi-colegio'
    | '/noticias/$id'
    | '/admin'
    | '/admin/documentos/nuevo'
    | '/admin/galeria/nueva'
    | '/admin/noticias/nueva'
    | '/admin/asistente'
    | '/admin/avisos'
    | '/admin/carrusel'
    | '/admin/docentes'
    | '/admin/documentos'
    | '/admin/eventos'
    | '/admin/faqs'
    | '/admin/galeria'
    | '/admin/libros'
    | '/admin/mensajes'
    | '/admin/noticias'
    | '/admin/preinscripciones'
    | '/admin/suscriptores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admisiones'
    | '/auth'
    | '/biblioteca'
    | '/bienestar'
    | '/calendario'
    | '/circulares'
    | '/contacto'
    | '/cre'
    | '/docentes'
    | '/faq'
    | '/galeria'
    | '/guias'
    | '/herramientas'
    | '/mi-colegio'
    | '/noticias/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/documentos/nuevo'
    | '/_authenticated/admin/galeria/nueva'
    | '/_authenticated/admin/noticias/nueva'
    | '/_authenticated/admin/asistente/'
    | '/_authenticated/admin/avisos/'
    | '/_authenticated/admin/carrusel/'
    | '/_authenticated/admin/docentes/'
    | '/_authenticated/admin/documentos/'
    | '/_authenticated/admin/eventos/'
    | '/_authenticated/admin/faqs/'
    | '/_authenticated/admin/galeria/'
    | '/_authenticated/admin/libros/'
    | '/_authenticated/admin/mensajes/'
    | '/_authenticated/admin/noticias/'
    | '/_authenticated/admin/preinscripciones/'
    | '/_authenticated/admin/suscriptores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdmisionesRoute: typeof AdmisionesRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BienestarRoute: typeof BienestarRoute
  CalendarioRoute: typeof CalendarioRoute
  CircularesRoute: typeof CircularesRoute
  ContactoRoute: typeof ContactoRoute
  CreRoute: typeof CreRoute
  DocentesRoute: typeof DocentesRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRoute
  GuiasRoute: typeof GuiasRoute
  HerramientasRoute: typeof HerramientasRoute
  MiColegioRoute: typeof MiColegioRoute
  NoticiasIdRoute: typeof NoticiasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mi-colegio': {
      id: '/mi-colegio'
      path: '/mi-colegio'
      fullPath: '/mi-colegio'
      preLoaderRoute: typeof MiColegioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes': {
      id: '/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof DocentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cre': {
      id: '/cre'
      path: '/cre'
      fullPath: '/cre'
      preLoaderRoute: typeof CreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulares': {
      id: '/circulares'
      path: '/circulares'
      fullPath: '/circulares'
      preLoaderRoute: typeof CircularesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienestar': {
      id: '/bienestar'
      path: '/bienestar'
      fullPath: '/bienestar'
      preLoaderRoute: typeof BienestarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admisiones': {
      id: '/admisiones'
      path: '/admisiones'
      fullPath: '/admisiones'
      preLoaderRoute: typeof AdmisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/suscriptores/': {
      id: '/_authenticated/admin/suscriptores/'
      path: '/admin/suscriptores'
      fullPath: '/admin/suscriptores/'
      preLoaderRoute: typeof AuthenticatedAdminSuscriptoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/preinscripciones/': {
      id: '/_authenticated/admin/preinscripciones/'
      path: '/admin/preinscripciones'
      fullPath: '/admin/preinscripciones/'
      preLoaderRoute: typeof AuthenticatedAdminPreinscripcionesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/noticias/': {
      id: '/_authenticated/admin/noticias/'
      path: '/admin/noticias'
      fullPath: '/admin/noticias/'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/mensajes/': {
      id: '/_authenticated/admin/mensajes/'
      path: '/admin/mensajes'
      fullPath: '/admin/mensajes/'
      preLoaderRoute: typeof AuthenticatedAdminMensajesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/libros/': {
      id: '/_authenticated/admin/libros/'
      path: '/admin/libros'
      fullPath: '/admin/libros/'
      preLoaderRoute: typeof AuthenticatedAdminLibrosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/galeria/': {
      id: '/_authenticated/admin/galeria/'
      path: '/admin/galeria'
      fullPath: '/admin/galeria/'
      preLoaderRoute: typeof AuthenticatedAdminGaleriaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/faqs/': {
      id: '/_authenticated/admin/faqs/'
      path: '/admin/faqs'
      fullPath: '/admin/faqs/'
      preLoaderRoute: typeof AuthenticatedAdminFaqsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/eventos/': {
      id: '/_authenticated/admin/eventos/'
      path: '/admin/eventos'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AuthenticatedAdminEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/documentos/': {
      id: '/_authenticated/admin/documentos/'
      path: '/admin/documentos'
      fullPath: '/admin/documentos/'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/docentes/': {
      id: '/_authenticated/admin/docentes/'
      path: '/admin/docentes'
      fullPath: '/admin/docentes/'
      preLoaderRoute: typeof AuthenticatedAdminDocentesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/carrusel/': {
      id: '/_authenticated/admin/carrusel/'
      path: '/admin/carrusel'
      fullPath: '/admin/carrusel/'
      preLoaderRoute: typeof AuthenticatedAdminCarruselIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/avisos/': {
      id: '/_authenticated/admin/avisos/'
      path: '/admin/avisos'
      fullPath: '/admin/avisos/'
      preLoaderRoute: typeof AuthenticatedAdminAvisosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/asistente/': {
      id: '/_authenticated/admin/asistente/'
      path: '/admin/asistente'
      fullPath: '/admin/asistente/'
      preLoaderRoute: typeof AuthenticatedAdminAsistenteIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/noticias/nueva': {
      id: '/_authenticated/admin/noticias/nueva'
      path: '/admin/noticias/nueva'
      fullPath: '/admin/noticias/nueva'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasNuevaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/galeria/nueva': {
      id: '/_authenticated/admin/galeria/nueva'
      path: '/admin/galeria/nueva'
      fullPath: '/admin/galeria/nueva'
      preLoaderRoute: typeof AuthenticatedAdminGaleriaNuevaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/documentos/nuevo': {
      id: '/_authenticated/admin/documentos/nuevo'
      path: '/admin/documentos/nuevo'
      fullPath: '/admin/documentos/nuevo'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosNuevoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDocumentosNuevoRoute: typeof AuthenticatedAdminDocumentosNuevoRoute
  AuthenticatedAdminGaleriaNuevaRoute: typeof AuthenticatedAdminGaleriaNuevaRoute
  AuthenticatedAdminNoticiasNuevaRoute: typeof AuthenticatedAdminNoticiasNuevaRoute
  AuthenticatedAdminAsistenteIndexRoute: typeof AuthenticatedAdminAsistenteIndexRoute
  AuthenticatedAdminAvisosIndexRoute: typeof AuthenticatedAdminAvisosIndexRoute
  AuthenticatedAdminCarruselIndexRoute: typeof AuthenticatedAdminCarruselIndexRoute
  AuthenticatedAdminDocentesIndexRoute: typeof AuthenticatedAdminDocentesIndexRoute
  AuthenticatedAdminDocumentosIndexRoute: typeof AuthenticatedAdminDocumentosIndexRoute
  AuthenticatedAdminEventosIndexRoute: typeof AuthenticatedAdminEventosIndexRoute
  AuthenticatedAdminFaqsIndexRoute: typeof AuthenticatedAdminFaqsIndexRoute
  AuthenticatedAdminGaleriaIndexRoute: typeof AuthenticatedAdminGaleriaIndexRoute
  AuthenticatedAdminLibrosIndexRoute: typeof AuthenticatedAdminLibrosIndexRoute
  AuthenticatedAdminMensajesIndexRoute: typeof AuthenticatedAdminMensajesIndexRoute
  AuthenticatedAdminNoticiasIndexRoute: typeof AuthenticatedAdminNoticiasIndexRoute
  AuthenticatedAdminPreinscripcionesIndexRoute: typeof AuthenticatedAdminPreinscripcionesIndexRoute
  AuthenticatedAdminSuscriptoresIndexRoute: typeof AuthenticatedAdminSuscriptoresIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminDocumentosNuevoRoute:
    AuthenticatedAdminDocumentosNuevoRoute,
  AuthenticatedAdminGaleriaNuevaRoute: AuthenticatedAdminGaleriaNuevaRoute,
  AuthenticatedAdminNoticiasNuevaRoute: AuthenticatedAdminNoticiasNuevaRoute,
  AuthenticatedAdminAsistenteIndexRoute: AuthenticatedAdminAsistenteIndexRoute,
  AuthenticatedAdminAvisosIndexRoute: AuthenticatedAdminAvisosIndexRoute,
  AuthenticatedAdminCarruselIndexRoute: AuthenticatedAdminCarruselIndexRoute,
  AuthenticatedAdminDocentesIndexRoute: AuthenticatedAdminDocentesIndexRoute,
  AuthenticatedAdminDocumentosIndexRoute:
    AuthenticatedAdminDocumentosIndexRoute,
  AuthenticatedAdminEventosIndexRoute: AuthenticatedAdminEventosIndexRoute,
  AuthenticatedAdminFaqsIndexRoute: AuthenticatedAdminFaqsIndexRoute,
  AuthenticatedAdminGaleriaIndexRoute: AuthenticatedAdminGaleriaIndexRoute,
  AuthenticatedAdminLibrosIndexRoute: AuthenticatedAdminLibrosIndexRoute,
  AuthenticatedAdminMensajesIndexRoute: AuthenticatedAdminMensajesIndexRoute,
  AuthenticatedAdminNoticiasIndexRoute: AuthenticatedAdminNoticiasIndexRoute,
  AuthenticatedAdminPreinscripcionesIndexRoute:
    AuthenticatedAdminPreinscripcionesIndexRoute,
  AuthenticatedAdminSuscriptoresIndexRoute:
    AuthenticatedAdminSuscriptoresIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdmisionesRoute: AdmisionesRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  BienestarRoute: BienestarRoute,
  CalendarioRoute: CalendarioRoute,
  CircularesRoute: CircularesRoute,
  ContactoRoute: ContactoRoute,
  CreRoute: CreRoute,
  DocentesRoute: DocentesRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRoute,
  GuiasRoute: GuiasRoute,
  HerramientasRoute: HerramientasRoute,
  MiColegioRoute: MiColegioRoute,
  NoticiasIdRoute: NoticiasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
